### ISSUE TITLE
Can't make the condition operator "IN / NOTIN" working

### ISSUE THREAD

**Issue by pfrayer** [ovh/utask#161]
**Describe the bug**

In a template step, I want to use the [condition operator](https://github.com/ovh/utask#condition-operators) `IN` / `NOTIN`. But it doesn't work: the assertion to check if a given value is `IN` / `NOTIN` a list of items is never true so I never match this condition.

Acccording to the doc:

> Note that the operators IN and NOTIN expect a list of acceptable values in the field value, instead of a single one. You can specify the separator character to use to split the values of the list using the field list_separator (default: ,). Each value of the list will be trimmed of its leading and trailing white spaces before comparison.

Here is my step:

```yaml
checkPlaybookStatus:
  description: Check the previously launched Ansible playbook's status is "successful"
  dependencies: [launchPlaybook]
  action:
    type: http
    configuration:
      url: http://some-url/api/v2/jobs/{{.step.launchPlaybook.output.id}}
      method: GET
  conditions:
    - type: check
      if:
        - value: '{{.step.checkPlaybookStatus.output.status}}'
          operator: IN
          expected: pending,waiting,running
      then:
        this: TO_RETRY
      message: Ansile playbook is still running
```

Here the value of `{{.step.checkPlaybookStatus.output.status}}` is "`pending`", I can see it in µTask GUI.
![Screenshot_2020-06-30_17-54-02](https://user-images.githubusercontent.com/7125014/86148299-bc2ede80-bafa-11ea-83a5-850c77d9694c.png)

In µTask logs I can see that my condition is not matched:
```
AfterRun: Step [checkPlaybookStatus] condition eval: Condition not met: expected pending to be found in list of acceptable values"
```
I tried to play with the format of the `expected:` entry in my template (using a yaml list; using another delimiter than `,` and specify it in `list_separator`; etc.) without success. The only solution I found is to divide this condition in 3 different `if` conditions trying to match the value with the `EQ` operator. It works, but using the `IN` operator would be much better.

Am I doing it wrong, or am I missing something in my template config ? Or is it a bug with the `IN` / `NOTIN` condition operators ?

**To Reproduce**
1. Have a template step that generate an output
2. Add a `conditions` block of type `check` with an `IN` operator; having at least one of the items in the `expected:` list that match your value
3. See the log `Condition not met`

**Expected behavior**
The condition should be matched. 

**utask version impacted by the bug**
v1.5.0

**Context which you are currently running utask**
Running inside a Docker container, built with this repo [Quick Start](https://github.com/ovh/utask#quick-start-). Not using any specific plugin.
