### ISSUE TITLE
Allow golang template in template field of subtask action

### ISSUE THREAD

**Issue by rclsilver** [ovh/utask#187]
**Is your feature request related to a problem? Please describe.**
In a template, i want to exexcute a subtask with a name provided as input of the main template.

**Describe the solution you'd like**
```yaml
...
inputs:
...
- name: installation_template
  description: Installation template
- name: installation_watchers
  description: Installation task watchers
  collection: true
...
steps:
...
  install-servers:
    foreach: '{{ field `step` `wait-scale` `output` `result` `result` | toJson }}'
    description: Follow server installation and do post-installation steps
    action:
      type: subtask
      configuration:
        template: '{{ .input.installation_template }}'
        input:
          ...
        watcher_usernames: '{{ .input.installation_watchers | toJson }}'
...
```
