### ISSUE TITLE
Allow to retrieve current resolution watchers

### ISSUE THREAD

**Issue by rclsilver** [ovh/utask#188]
**Is your feature request related to a problem? Please describe.**
In a template, i'm creating a subtask. I would like to define watcher_usernames with the main template value.

**Describe the solution you'd like**
```yaml
...
inputs:
...
steps:
...
  install-servers:
    foreach: '{{ field `step` `wait-scale` `output` `result` `result` | toJson }}'
    description: Follow server installation and do post-installation steps
    action:
      type: subtask
      configuration:
        template: install-server
        input:
          ...
        watcher_usernames: '{{ .watcher_usernames | toJson }}'
...
```

**Describe alternatives you've considered**
Currently, when i create a new task, i've an input with a list of usernames.
