### ISSUE TITLE
templating: field operator pipe support

### ISSUE THREAD

**Issue by rbeuque74** [ovh/utask#200]
**Describe the solution you'd like**
`field` templating function only looks inside the templating global context when called.
In case we want to use it in a pipe context, we should take as the first parameter the context on which to apply.

Example: (context)
```yaml
"step":
  "first":
    "output": 
       "result": 
           "my-payload": "{\"common-name\":\"utask.example.org\",\"id\":32}"
```

To retrieve the `common_name` key, we could use templating like this:
```
{{ field `step` `first` `output` `result` `my-payload` | fromJson | fieldFrom `common-name` }}
```

The `fieldFrom` operator would take the context from the first argument, instead of the global task/resolution context; hence enabling the pipe operator to work as expected.
