### ISSUE TITLE
parent task not updating when subtask enters FATAL_ERROR state

### ISSUE THREAD

**Issue by omer21104** [ovh/utask#492]
**Describe the bug**
in my scenario, i have a task, which creates a subtask. when the subtask fails at some point (enters FATAL_ERROR state), the parent task is not updating and is stuck in WAITING state forever.

**To Reproduce**
to reproduce, i created dummy parent and sub tasks to illustrate the problem:
parent task:
```
name: parent-task
description: parent task
long_description: parent task
 
title_format: parent-task
 
allow_all_resolver_usernames: true
auto_runnable: true
blocked: false
hidden: false
 
retry_max: 1  
steps:
  callSub:
    description: call the subtask
    action:
      type: subtask
      configuration:
        template: my-subtask
        resolver_usernames: '["admin"]'
        resolver_groups: '["admins"]'
```

my-subtask:
```
name: my-subtask
description: my-subtask
long_description: my-subtask
 
title_format: my-subtask
 
allow_all_resolver_usernames: true
auto_runnable: true
blocked: false
hidden: false
 
retry_max: 1
steps:
  echoHello:
    description: echo hello
    action:
      type: echo
      configuration:
        output: hello
    conditions:
      - type: check
        if:
          - value: "a"
            operator: EQ 
            expected: "a"
        then:
          this: FATAL_ERROR

```

**Expected behavior**
i expect the parent task to enter FATAL ERROR state when a subtask enters FATAL_ERROR

**uTask version impacted by the bug**
v1.28.X and up

**Context which you are currently running utask**
Inside a Docker container, running the official docker image, through docker-compose provided by you.

**Additional context**
i also tried previous versions (1.21 and 1.23) of uTask and the latest version.
if this is a feature, i would very much like to know how to control this behaviour, as i could not find and example or way to handle this.
